// Tips
var greenLivingTips = [
    "Use natural light instead of artificial lighting whenever possible.",
    "Switch to energy-efficient LED light bulbs.",
    "Turn off lights and unplug electronic devices when not in use.",
    "Use power strips to easily turn off multiple electronics at once.",
    "Opt for energy-efficient appliances.",
    "Set your thermostat a few degrees lower in winter and a few degrees higher in summer.",
    "Install a programmable thermostat to regulate your home's temperature.",
    "Insulate your home properly to reduce energy consumption.",
    "Use ceiling fans instead of air conditioning whenever possible.",
    "Dry your clothes on a clothesline instead of using a dryer.",
    "Collect rainwater for watering plants and gardens.",
    "Fix leaky faucets and pipes promptly.",
    "Take shorter showers to conserve water.",
    "Install low-flow showerheads and faucets.",
    "Use a broom instead of a hose to clean outdoor spaces.",
    "Choose eco-friendly cleaning products or make your own.",
    "Recycle paper, plastic, glass, and metal.",
    "Compost organic waste to create nutrient-rich soil.",
    "Reduce food waste by planning meals and storing leftovers properly.",
    "Buy locally grown and seasonal produce.",
    "Support farmers' markets and organic food stores.",
    "Reduce meat consumption and choose plant-based meals.",
    "Choose products with minimal packaging or opt for package-free alternatives.",
    "Bring your own reusable bags when shopping.",
    "Use a reusable water bottle instead of disposable plastic bottles.",
    "Avoid single-use plastics, such as straws and utensils.",
    "Carry a reusable coffee mug or thermos.",
    "Pack waste-free lunches using reusable containers.",
    "Use cloth napkins instead of disposable paper napkins.",
    "Repair and repurpose items instead of throwing them away.",
    "Donate or sell unwanted items instead of discarding them.",
    "Buy second-hand items whenever possible.",
    "Choose durable products that will last longer.",
    "Use rechargeable batteries instead of disposable ones.",
    "Use a manual can opener instead of an electric one.",
    "Opt for digital documents and emails instead of printing.",
    "Use both sides of a piece of paper before recycling it.",
    "Use eco-friendly and non-toxic household products.",
    "Avoid using pesticides and opt for natural pest control methods.",
    "Plant native species in your garden to support local ecosystems.",
    "Create a bee-friendly garden by planting flowers that attract pollinators.",
    "Install bird feeders and birdhouses to support local bird populations.",
    "Use natural fertilizers and compost instead of synthetic chemicals.",
    "Use a push mower or an electric mower instead of a gas-powered one.",
    "Start a community garden or join a local gardening club.",
    "Support renewable energy initiatives in your community.",
    "Install solar panels on your home to generate clean energy.",
    "Use public transportation, carpool, bike, or walk instead of driving alone.",
    "Maintain your vehicle properly to maximize fuel efficiency.",
    "Combine errands and trips to minimize driving.",
    "Use eco-friendly alternatives for transportation, such as electric bikes or scooters.",
    "Choose eco-friendly options when booking vacations, such as eco-resorts or camping.",
    "Explore local outdoor activities and nature trails.",
    "Volunteer for environmental organizations and initiatives.",
    "Participate in local clean-up events and beach or park restoration projects.",
    "Support environmental legislation and advocate for sustainable practices.",
    "Use reusable cloth diapers instead of disposable ones.",
    "Breastfeed your baby, if possible, to reduce waste from formula packaging.",
    "Choose eco-friendly and non-toxic baby products.",
    "Use cloth wipes instead of disposable baby wipes.",
    "Buy eco-friendly pet products and food.",
    "Adopt a pet from a shelter instead of buying from a breeder.",
    "Spay or neuter your pets to reduce overpopulation.",
    "Scoop pet waste and dispose of it properly.",
    "Use eco-friendly and biodegradable cat litter.",
    "Support eco-friendly clothing brands that use sustainable materials.",
    "Wash clothes in cold water to save energy.",
    "Line dry clothes instead of using a dryer.",
    "Mend or repair clothes instead of replacing them.",
    "Donate unwanted clothing to thrift stores or clothing drives.",
    "Choose natural fibers, such as organic cotton or hemp, for clothing.",
    "Avoid fast fashion and opt for quality clothing that lasts longer.",
    "Choose eco-friendly options for personal care products, such as shampoo and soap.",
    "Use a safety razor or an electric razor instead of disposable razors.",
    "Avoid excessive packaging when buying personal care products.",
    "Use menstrual cups or reusable cloth pads instead of disposable tampons and pads.",
    "Choose eco-friendly options for dental care, such as bamboo toothbrushes and biodegradable floss.",
    "Use rechargeable electronic devices instead of disposable ones.",
    "Recycle or properly dispose of electronic waste.",
    "Choose eco-friendly options for office supplies, such as recycled paper and refillable pens.",
    "Print on both sides of a paper or use scrap paper for notes.",
    "Set your computer and other devices to energy-saving mode.",
    "Turn off your computer at night instead of leaving it on standby mode.",
    "Reduce junk mail by opting out of unsolicited mailings.",
    "Support companies and brands that prioritize sustainability and ethical practices.",
    "Educate yourself and stay informed about environmental issues.",
    "Share green living tips with friends, family, and coworkers.",
    "Encourage others to adopt eco-friendly habits and practices.",
    "Advocate for renewable energy in your community and workplace.",
    "Support local environmental initiatives and projects.",
    "Participate in community gardens or urban farming projects.",
    "Host or attend eco-friendly events and gatherings.",
    "Use eco-friendly alternatives for gift wrapping, such as cloth bags or recycled paper.",
    "Choose eco-friendly gifts, such as plants, reusable products, or experiences.",
    "Use rechargeable batteries for children's toys and electronic devices.",
    "Teach children about the importance of conserving resources and protecting the environment.",
    "Involve children in gardening and composting activities.",
    "Encourage children to participate in recycling and waste reduction efforts.",
    "Support and promote sustainable and ethical businesses in your community.",
    "Be mindful of your water usage and avoid wasteful practices.",
    "Avoid using disposable plates, cups, and utensils for parties and gatherings.",
    "Use natural and non-toxic pest control methods in your home and garden.",
    "Practice mindful consumption and avoid impulse buying.",
    "Opt for digital subscriptions instead of physical newspapers and magazines.",
    "Reduce your reliance on paper towels and use cloth towels instead.",
    "Choose eco-friendly options for household furniture and decor.",
    "Use natural and non-toxic materials for home renovations.",
    "Reduce your overall consumption of resources and materials.",
    "Avoid using plastic wrap and use reusable food storage containers.",
    "Choose eco-friendly options for home improvement projects.",
    "Use non-toxic and biodegradable cleaning products for your car.",
    "Support car-sharing programs and carpooling initiatives.",
    "Use public bike-sharing programs or rent bicycles for short trips.",
    "Choose eco-friendly options for car maintenance, such as low VOC paints and recycled oil.",
    "Avoid idling your car and turn it off when parked for extended periods.",
    "Use eco-friendly alternatives for party decorations, such as reusable banners and fabric tablecloths.",
    "Choose eco-friendly options for pet toys and bedding.",
    "Use eco-friendly alternatives for home fragrances, such as essential oils and natural air fresheners.",
    "Support eco-friendly and sustainable fashion brands that prioritize fair trade practices.",
    "Opt for eco-friendly flooring options, such as bamboo or cork.",
    "Use eco-friendly alternatives for home insulation, such as recycled denim or cellulose.",
    "Choose eco-friendly options for home appliances, such as energy-efficient refrigerators and washing machines.",
    "Use eco-friendly alternatives for home furniture, such as reclaimed wood or bamboo.",
    "Opt for eco-friendly options for window coverings, such as bamboo blinds or organic cotton curtains.",
    "Use eco-friendly alternatives for home electronics, such as energy-efficient TVs and computers.",
    "Choose eco-friendly options for home decor, such as reclaimed or recycled materials.",
    "Use eco-friendly alternatives for home heating, such as solar panels or geothermal systems.",
    "Opt for eco-friendly options for home cooling, such as natural ventilation or energy-efficient air conditioners.",
    "Use eco-friendly alternatives for home water filtration, such as activated charcoal or ceramic filters.",
    "Choose eco-friendly options for home security systems, such as solar-powered outdoor lights or smart sensors.",
    "Use eco-friendly alternatives for home automation systems, such as energy-efficient smart thermostats or lighting controls.",
    "Opt for eco-friendly options for home entertainment systems, such as energy-efficient TVs or speakers.",
    "Choose eco-friendly options for home office equipment, such as energy-efficient printers or recycled paper.",
    "Use eco-friendly alternatives for home storage solutions, such as bamboo or fabric baskets.",
    "Opt for eco-friendly options for home organization systems, such as recycled plastic or sustainable wood.",
    "Choose eco-friendly options for home water-saving devices, such as low-flow showerheads or dual-flush toilets.",
    "Use eco-friendly alternatives for home cleaning tools, such as microfiber cloths or natural bristle brushes.",
    "Opt for eco-friendly options for home gardening tools, such as bamboo or stainless steel.",
    "Choose eco-friendly options for home cooking utensils, such as bamboo or stainless steel.",
    "Use eco-friendly alternatives for home food storage, such as glass containers or beeswax wraps.",
    "Opt for eco-friendly options for home laundry equipment, such as energy-efficient washing machines or clotheslines.",
    "Choose eco-friendly options for home bathroom fixtures, such as water-saving toilets or faucets.",
    "Use eco-friendly alternatives for home bathroom accessories, such as bamboo or recycled plastic.",
    "Opt for eco-friendly options for home air purification, such as natural plants or activated charcoal.",
    "Choose eco-friendly options for home soundproofing, such as recycled insulation or acoustic panels.",
    "Use eco-friendly alternatives for home paint and finishes, such as low VOC or natural pigments.",
    "Opt for eco-friendly options for home flooring, such as bamboo or reclaimed wood.",
    "Choose eco-friendly options for home roofing, such as solar panels or reflective materials.",
    "Use eco-friendly alternatives for home siding, such as reclaimed or recycled materials.",
    "Opt for eco-friendly options for home windows and doors, such as energy-efficient glass or recycled materials.",
    "Choose eco-friendly options for home plumbing, such as low-flow fixtures or recycled pipes.",
    "Use eco-friendly alternatives for home electrical wiring, such as recycled copper or aluminum.",
    "Opt for eco-friendly options for home heating systems, such as solar or geothermal.",
    "Choose eco-friendly options for home cooling systems, such as natural ventilation or energy-efficient air conditioners.",
    "Use eco-friendly alternatives for home insulation, such as recycled denim or cellulose.",
    "Opt for eco-friendly options for home water filtration, such as activated charcoal or ceramic filters.",
    "Choose eco-friendly options for home lighting, such as LED or CFL bulbs.",
    "Use eco-friendly alternatives for home soundproofing, such as recycled insulation or acoustic panels.",
    "Opt for eco-friendly options for home furniture, such as reclaimed or sustainably sourced materials.",
    "Choose eco-friendly options for home decor, such as natural fabrics or recycled materials.",
    "Use eco-friendly alternatives for home electronics, such as energy-efficient TVs or computers.",
    "Opt for eco-friendly options for home appliances, such as energy-efficient refrigerators or washing machines.",
    "Choose eco-friendly options for home cleaning products, such as natural or biodegradable formulas.",
    "Use eco-friendly alternatives for home air fresheners, such as essential oils or natural sprays.",
    "Opt for eco-friendly options for home laundry detergents, such as plant-based or biodegradable formulas.",
    "Choose eco-friendly options for home personal care products, such as natural or organic ingredients.",
    "Use eco-friendly alternatives for home pet care products, such as natural or biodegradable formulas.",
    "Opt for eco-friendly options for home baby care products, such as organic or non-toxic ingredients.",
    "Choose eco-friendly options for home gardening supplies, such as organic fertilizers or compost.",
    "Use eco-friendly alternatives for home pest control, such as natural or non-toxic methods.",
    "Opt for eco-friendly options for home water conservation, such as rainwater harvesting or greywater systems.",
    "Choose eco-friendly options for home energy management, such as smart thermostats or energy monitors.",
    "Use eco-friendly alternatives for home waste management, such as composting or recycling systems.",
    "Opt for eco-friendly options for home security, such as solar-powered outdoor lights or smart locks.",
    "Choose eco-friendly options for home automation, such as energy-efficient smart devices or sensors.",
    "Use eco-friendly alternatives for home entertainment, such as energy-efficient TVs or speakers.",
    "Opt for eco-friendly options for home office supplies, such as recycled paper or refillable pens.",
    "Print on both sides of a paper or use scrap paper for notes.",
    "Set your computer and other devices to energy-saving mode.",
    "Turn off your computer at night instead of leaving it on standby mode.",
    "Reduce junk mail by opting out of unsolicited mailings.",
    "Support companies and brands that prioritize sustainability and ethical practices.",
    "Educate yourself and stay informed about environmental issues.",
    "Share green living tips with friends, family, and coworkers.",
    "Encourage others to adopt eco-friendly habits and practices.",
    "Advocate for renewable energy in your community and workplace.",
    "Support local environmental initiatives and projects.",
    "Participate in community gardens or urban farming projects.",
    "Host or attend eco-friendly events and gatherings.",
    "Use eco-friendly alternatives for gift wrapping, such as cloth bags or recycled paper.",
    "Choose eco-friendly gifts, such as plants, reusable products, or experiences.",
    "Use rechargeable batteries for children's toys and electronic devices.",
    "Teach children about the importance of conserving resources and protecting the environment.",
    "Involve children in gardening and composting activities.",
    "Encourage children to participate in recycling and waste reduction efforts.",
    "Support and promote sustainable and ethical businesses in your community.",
    "Be mindful of your water usage and avoid wasteful practices.",
    "Avoid using disposable plates, cups, and utensils for parties and gatherings.",
    "Use natural and non-toxic pest control methods in your home and garden.",
    "Practice mindful consumption and avoid impulse buying.",
    "Opt for digital subscriptions instead of physical newspapers and magazines.",
    "Reduce your reliance on paper towels and use cloth towels instead.",
    "Choose eco-friendly options for household furniture and decor.",
    "Use natural and non-toxic materials for home renovations.",
    "Reduce your overall consumption of resources and materials.",
    "Avoid using plastic wrap and use reusable food storage containers.",
    "Choose eco-friendly options for home improvement projects.",
    "Use non-toxic and biodegradable cleaning products for your car.",
    "Support car-sharing programs and carpooling initiatives.",
    "Use public bike-sharing programs or rent bicycles for short trips.",
    "Choose eco-friendly options for car maintenance, such as low VOC paints and recycled oil.",
    "Avoid idling your car and turn it off when parked for extended periods.",
    "Use eco-friendly alternatives for party decorations, such as reusable banners and fabric tablecloths.",
    "Choose eco-friendly options for pet toys and bedding.",
    "Use eco-friendly alternatives for home fragrances, such as essential oils and natural air fresheners.",
    "Support eco-friendly and sustainable fashion brands that prioritize fair trade practices.",
    "Opt for eco-friendly flooring options, such as bamboo or cork.",
    "Use eco-friendly alternatives for home insulation, such as recycled denim or cellulose.",
    "Choose eco-friendly options for home appliances, such as energy-efficient refrigerators and washing machines.",
    "Use eco-friendly alternatives for home furniture, such as reclaimed wood or bamboo.",
    "Opt for eco-friendly options for window coverings, such as bamboo blinds or organic cotton curtains.",
    "Use eco-friendly alternatives for home electronics, such as energy-efficient TVs and computers.",
    "Choose eco-friendly options for home decor, such as reclaimed or recycled materials.",
    "Use eco-friendly alternatives for home heating, such as solar panels or geothermal systems.",
    "Opt for eco-friendly options for home cooling, such as natural ventilation or energy-efficient air conditioners.",
    "Use eco-friendly alternatives for home water filtration, such as activated charcoal or ceramic filters.",
    "Choose eco-friendly options for home security systems, such as solar-powered outdoor lights or smart sensors.",
    "Use eco-friendly alternatives for home automation systems, such as energy-efficient smart thermostats or lighting controls.",
    "Opt for eco-friendly options for home entertainment systems, such as energy-efficient TVs or speakers.",
    "Choose eco-friendly options for home office equipment, such as energy-efficient printers or recycled paper.",
    "Use eco-friendly alternatives for home storage solutions, such as bamboo or fabric baskets.",
    "Opt for eco-friendly options for home organization systems, such as recycled plastic or sustainable wood.",
    "Choose eco-friendly options for home water-saving devices, such as low-flow showerheads or dual-flush toilets.",
    "Use eco-friendly alternatives for home cleaning tools, such as microfiber cloths or natural bristle brushes.",
    "Opt for eco-friendly options for home gardening tools, such as bamboo or stainless steel.",
    "Choose eco-friendly options for home cooking utensils, such as bamboo or stainless steel.",
    "Use eco-friendly alternatives for home food storage, such as glass containers or beeswax wraps.",
    "Opt for eco-friendly options for home laundry equipment, such as energy-efficient washing machines or clotheslines.",
    "Choose eco-friendly options for home bathroom fixtures, such as water-saving toilets or faucets.",
    "Use eco-friendly alternatives for home bathroom accessories, such as bamboo or recycled plastic.",
    "Opt for eco-friendly options for home air purification, such as natural plants or activated charcoal.",
    "Choose eco-friendly options for home soundproofing, such as recycled insulation or acoustic panels.",
    "Use eco-friendly alternatives for home paint and finishes, such as low VOC or natural pigments.",
    "Opt for eco-friendly options for home flooring, such as bamboo or reclaimed wood.",
    "Choose eco-friendly options for home roofing, such as solar panels or reflective materials.",
    "Use eco-friendly alternatives for home siding, such as reclaimed or recycled materials.",
    "Opt for eco-friendly options for home windows and doors, such as energy-efficient glass or recycled materials.",
    "Choose eco-friendly options for home plumbing, such as low-flow fixtures or recycled pipes.",
    "Use eco-friendly alternatives for home electrical wiring, such as recycled copper or aluminum.",
    "Opt for eco-friendly options for home heating systems, such as solar or geothermal.",
    "Choose eco-friendly options for home cooling systems, such as natural ventilation or energy-efficient air conditioners.",
    "Use eco-friendly alternatives for home insulation, such as recycled denim or cellulose.",
    "Opt for eco-friendly options for home water filtration, such as activated charcoal or ceramic filters.",
    "Choose eco-friendly options for home lighting, such as LED or CFL bulbs.",
    "Use eco-friendly alternatives for home soundproofing, such as recycled insulation or acoustic panels.",
    "Opt for eco-friendly options for home furniture, such as reclaimed or sustainably sourced materials.",
    "Choose eco-friendly options for home decor, such as natural fabrics or recycled materials.",
    "Use eco-friendly alternatives for home electronics, such as energy-efficient TVs or computers.",
    "Opt for eco-friendly options for home appliances, such as energy-efficient refrigerators or washing machines.",
    "Choose eco-friendly options for home cleaning products, such as natural or biodegradable formulas.",
    "Use eco-friendly alternatives for home air fresheners, such as essential oils or natural sprays.",
    "Opt for eco-friendly options for home laundry detergents, such as plant-based or biodegradable formulas.",
    "Choose eco-friendly options for home personal care products, such as natural or organic ingredients.",
    "Use eco-friendly alternatives for home pet care products, such as natural or biodegradable formulas.",
    "Opt for eco-friendly options for home baby care products, such as organic or non-toxic ingredients.",
    "Choose eco-friendly options for home gardening supplies, such as organic fertilizers or compost.",
    "Use eco-friendly alternatives for home pest control, such as natural or non-toxic methods.",
    "Opt for eco-friendly options for home water conservation, such as rainwater harvesting or greywater systems.",
    "Choose eco-friendly options for home energy management, such as smart thermostats or energy monitors.",
    "Use eco-friendly alternatives for home waste management, such as composting or recycling systems.",
    "Opt for eco-friendly options for home security, such as solar-powered outdoor lights or smart locks.",
    "Choose eco-friendly options for home automation, such as energy-efficient smart devices or sensors.",
    "Use eco-friendly alternatives for home entertainment, such as energy-efficient TVs or speakers.",
    "Opt for eco-friendly options for home office supplies, such as recycled paper or refillable pens."
];  
 
//Random Tips Genrator
function generateRandomTips() {
    var tipsContainer = document.getElementById("tips-container");

    for (var i = 0; i < 1; i++) {
        var randomIndex = Math.floor(Math.random() * greenLivingTips.length);
        var randomTip = greenLivingTips[randomIndex];

        var tipElement = document.createElement("div");
        tipElement.classList.add("tip");

        var tipHeading = document.createElement("h2");
        tipHeading.textContent = "Tip:";
        tipHeading.classList.add("tip-heading")

        var tipContent = document.createElement("p");
        tipContent.textContent = randomTip;
        tipContent.classList.add("text")

        tipElement.appendChild(tipHeading);
        tipElement.appendChild(tipContent);

        tipsContainer.appendChild(tipElement);
    }
}

//New Tips Button Function
function showNewTip() {
    var tipsContainer = document.getElementById("tips-container");
    tipsContainer.innerHTML = ""; // Clear the previous tip

    generateRandomTips();
}

var newTipBtn = document.getElementById("new-tip");
newTipBtn.addEventListener("click", showNewTip);

//Load a Random Tip by default
window.addEventListener("load", generateRandomTips);